### ISSUE TITLE
is it possible to use this extension as a bookmarklet?

### ISSUE THREAD

**Issue by th0mass** [Ashish-Bansal/audio-only-youtube#1]
Can you lead me to the most appropriate way for this purpose? thanks

**Comment by Ashish-Bansal** [comment]
Hi Thomas, I don't think there's any way by which bookmarklet can use the Chrome's API. So, it isn't really possible to use this extension as a bookmarklet.

Anyway, If you really want to create a bookmarklet yourself from the scratch, then you can just get the direct Audio URL by sending a request, containing YouTube Video ID, to your own Web service hosted on a server. Once you got that direct URL, you just have to replace the player's source with that URL using JS.
