### ISSUE TITLE
Show thumbnail overlay image

### ISSUE THREAD

**Issue by zekrom-vale** [Ashish-Bansal/audio-only-youtube#10]
`.ytp-thumbnail-overlay-image `remove `display:none`
`.ytp-large-play-button` add `display:none`

JS code:

```
document.getElementsByClassName('ytp-thumbnail-overlay-image')[0].style.display= '';
document.getElementsByClassName('ytp-large-play-button')[0]= 'none';
```

**Comment by zekrom-vale** [comment]
Note! I cannot use only CSS to do this as it will ALWAYS do this!

**Comment by Ashish-Bansal** [comment]
We already have option to show thumbnail image now.
