### ISSUE TITLE
Micro-cuts or drops

### ISSUE THREAD

**Issue by marianowadel** [Ashish-Bansal/audio-only-youtube#12]
While using the extension the audio drops/skips forward and goes back randomly for a tenth of second or so. Pretty fast but still audible. 
I'm using Chrome 60.0.3112.90 64 bits on Ubuntu 16.04 LTS on a Lenovo Thinkpad T430 w/ Intel i5 Ivy Bridge. Light use, no CPU intensive tasks at the time.
Great job!

**Comment by Ashish-Bansal** [comment]
Sorry, I missed this issue. Just came across this. 
Well, that's quite weird. I never experienced this.  Can you please check if Chrome's CPU usage gets high at that time ?

**Comment by marianowadel** [comment]
Hey Ashish, thank you for your answer! I'm a little ashamed of admitting this, but my headphones died the day after I reported this "issue", so I'm guessing they were the culprit. I repaired them and I'm using your extension now without any hiccups.  I'll test a little more but I'm pretty sure the extension works as expected. Again I'm very sorry!
Cheers

**Comment by Ashish-Bansal** [comment]
No problem :)
