### ISSUE TITLE
Extension doesn't work with livestreaming.

### ISSUE THREAD

**Issue by Thehail** [Ashish-Bansal/audio-only-youtube#14]
Just what title says. Simply works for some moments but... give a try and you will know what happens.

**Comment by craftwar** [comment]
streamlink doesn't provide audio only in youtube live.
https://github.com/streamlink/streamlink
I don't think youtube live provides audio only stream. Just recognize it's live and don't apply to it.
Do you mind sharing knowledge about audio url? I just apply your logic, don't know why.

**Comment by craftwar** [comment]
bug fix or whatever
I get youtube audio in streamlink (m4a and webm)
This is possible.

**Comment by Ashish-Bansal** [comment]
> Do you mind sharing knowledge about audio url? I just apply your logic, don't know why.

I intercept all the requests sent by the chrome and get the audio stream's URL. Then I replace the youtube player's source with that stream's URL.

>I get youtube audio in streamlink (m4a and webm)
> This is possible.

That's good to know!

**Comment by craftwar** [comment]
I know that, I mean how you know what url parameters to set. After more tests, not all live supports audio. There are still some youtube plugin bugs in streamlink.

**Comment by Ashish-Bansal** [comment]
> I mean how you know what url parameters to set

I remove the URL parameters which are responsible for requesting partial content from youtube.

**Comment by p0we7** [comment]
Still doesn't support livestreaming now？

I try to play a live and will response a error on youtube

**Comment by arminmacx** [comment]
Hi, Sorry to ask it again but any news on how we can listen to live youtube with this extension? or did you fix it?

**Comment by Ashish-Bansal** [comment]
Hi @arminmacx, 

No it hasn't been fixed. 



On the side note, in case anyone is interested in fixing it, I can add technical details I found just now from the live streaming requests. This extension doesn't work for the live youtube because we can't get one audio stream link for live streams. The streams are being served in segments of few seconds. Those segments are specified by sequence no.

![image](https://user-images.githubusercontent.com/6122999/53710816-06e80a00-3e65-11e9-83c2-1ff6c9998dee.png)


```
https://r2---sn-oxu2a0npo-a0ie.googlevideo.com/videoplayback?live=1&gcr=in&hang=1&id=cnugE0LByiU.1&c=WEB&cmbypass=yes&gir=yes&pcm2cms=yes&signature=7505E0A34C18344EF541D39031FCD0F9874D588F.DDD03B3ED765ED3DDB4C2C59E8889D4897C3F47C&ip=103.41.26.191&requiressl=yes&initcwndbps=861250&ms=lv&itag=135&mt=1551673882&mv=m&aitags=133%2C134%2C135%2C160&sparams=aitags%2Ccmbypass%2Cei%2Cgcr%2Cgir%2Chang%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clive%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnoclen%2Cpcm2cms%2Cpl%2Crequiressl%2Csource%2Cexpire&ipbits=0&keepalive=yes&mm=32&mn=sn-oxu2a0npo-a0ie&ei=f6p8XO7MKIvUkAOirL3AAQ&expire=1551695583&noclen=1&mime=video%2Fmp4&pl=24&source=yt_live_broadcast&key=yt6&alr=yes&cpn=aXkZ5GooXaFVGlW1&cver=2.20190227&sq=681091&rn=133&rbuf=20071
```

This sequence no. is specified using `sq` query parameter. We can keep incrementing this sequence no. and play the audio.

**Comment by Ashish-Bansal** [comment]
It will required good amount of DOM manipulation related to Youtube's player. Instead I would suggest just disabling this extension programmatically on the live videos so that it doesn't involve bad UX.
