### ISSUE TITLE
Scope permissions

### ISSUE THREAD

**Issue by Esteban-Rocha** [Ashish-Bansal/audio-only-youtube#21]
Read and change all your data on the websites you visit

 "permissions": [
    "tabs",
    "webRequest",
    "*://*/*",
    "webRequestBlocking",
    "storage"
  ],

I think as many other people that permissions should be scoped only to youtube.com* sites, please let know if this will be implemented, thanks.

**Comment by Ashish-Bansal** [comment]
Hi @Esteban-Rocha ,

This was done so that it can work in the websites which have embedded youtube videos. That's we hook it up for all the websites.

Check out #2 for more details.

Thanks!

**Comment by Ashish-Bansal** [comment]
This issue has been fixed in https://github.com/Ashish-Bansal/audio-only-youtube/commit/aee91e42517f9759d7e3668daed45bb8a750129d
