### ISSUE TITLE
Use on all kinds of websites?

### ISSUE THREAD

**Issue by orschiro** [Ashish-Bansal/audio-only-youtube#23]
This extension is such a good idea to save bandwidth, not only on YouTube but all kinds of sites where videos are shown. 

Is it possible to easily expand beyond YouTube?

**Comment by craftwar** [comment]
No, specific rules to different sites. And some sites doesn't provide audio only stream.

**Comment by orschiro** [comment]
How do I know if they provide an audio stream?

Example: http://www.pcgames.de/Star-Citizen-Spiel-3481/News/Video-Frankfurter-Studio-Entwicklungsfortschritte-1249312/

**Comment by orschiro** [comment]
Found a workaround. Get the URL of the video and play it with `mpv --no-video`. :-)

**Comment by craftwar** [comment]
It still downloads full stream, not audio only. But player plays audio only.
You need read platform API doc or use network monitor to find out audio stream.

**Comment by orschiro** [comment]
> It still downloads full stream, not audio only. But player plays audio only.

True but at least it consumes less battery that way...

**Comment by Ashish-Bansal** [comment]
@orschiro Yes, @craftwar is right. Although if anyone is willing to add support(in a clean way) for other sites which provide audio stream, I'll surely accept it.

**Comment by Ashish-Bansal** [comment]
I believe adding support for more sites would be difficult to maintain. So, I would say it "wontfix".
