### ISSUE TITLE
No longer blocks video thumbnails?

### ISSUE THREAD

**Issue by taviandir** [Ashish-Bansal/audio-only-youtube#31]
### Description
I've been using this extension for a few months ago. Recently, I noticed that it now shows a thumbnail for the video playing. To be clear, this only applies to the actual video element, for the video that is currently playing. The suggestions' thumbnails are blocked as expected.
See images below:

### Expected (previous) behaviour
![Imgur link](https://i.imgur.com/CYhTARD.png)

### Actual (current) behaviour
![Imgur link](https://i.imgur.com/LetdhIJ.png)

Is this due to some CSS change on youtube? Or have there been changes been made to this extension? If the latter, could we please have an option to toggle this behaviour on or off? 
I mainly use this extension in order to NOT SEE even the thumbnail - since some mixes I enjoy listening to sadly have "questionable" (borderline NSFW) images and thumbnails.

**Comment by Esteban-Rocha** [comment]
Hey, did you check that this is properly set? Just go to the extension options, this option is there a while ago.  

--- 

![image](https://user-images.githubusercontent.com/5914592/41689488-6c2b7ac4-74b6-11e8-95e6-3b04b64d4970.png)

**Comment by taviandir** [comment]
I swear I went into the Options before posting this, and did not see that
screen. But I can see it now. Is it a recent addition? Just enabled it and
it seems to work as expected.

**Comment by Esteban-Rocha** [comment]
I don't recall exactly.. but yeah some weeks ago at least.

**Comment by Ashish-Bansal** [comment]
@taviandir Yeah, it was a recent addition.
