### ISSUE TITLE
When can Live video be supported?

### ISSUE THREAD

**Issue by DolorHunter** [Ashish-Bansal/audio-only-youtube#51]
Hi developer,
I've used your script already. Really good on most video!!
However, I want to use it to listen to music online. I've noticed that most script can't deal with Live Video. Maybe there is a technical issue for it, but  I still want to know if there is a chance to have a Live Video supported version later.
Really like what you are working on. 
Thank you.

**Comment by Ashish-Bansal** [comment]
Hi,

Please have a look at https://github.com/Ashish-Bansal/audio-only-youtube/issues/14

I don't really plan to support live streams.
