### ISSUE TITLE
Does it preserve battery life?

### ISSUE THREAD

**Issue by orschiro** [Ashish-Bansal/audio-only-youtube#55]
Wondering, does it only preserve bandwidth or also battery life?

**Comment by lefuturiste** [comment]
Well, from my point of view the extension block all requests of the video stream just before the request actually is made. So in a certain way yes it can clearly preserve battery life because you browser won't have to deal with the video stream in order to decode it and show it on the screen.

**Comment by orschiro** [comment]
Great thanks!

Le_Futuriste <notifications@github.com> schrieb am So. 3. Mai 2020 um 14:24:

**Comment by Ashish-Bansal** [comment]
@lefuturiste Thanks for your input!
