### ISSUE TITLE
Limit suspicious permissions

### ISSUE THREAD

**Issue by alexchandel** [Ashish-Bansal/audio-only-youtube#62]
This extension currently requires `Read and change your data on all websites`.  That is very suspicious, as the extension is only for Youtube.  Please limit the required permissions to only Youtube & Google Video domains.

**Comment by MingweiSamuel** [comment]
#21 #2 
(It’s to allow the extension to work on embedded videos on other sites. There’s probably an argument to have it either way but wide permissions aren’t baseless)

**Comment by alexchandel** [comment]
Is it possible to scope the extension to only Youtube iframes?

**Comment by Ashish-Bansal** [comment]
@alexchandel AFAIK, no it's not possible. In case someone is aware of a way to do it, I would happily accept that patch.

**Comment by Ashish-Bansal** [comment]
This issue has been fixed in https://github.com/Ashish-Bansal/audio-only-youtube/commit/aee91e42517f9759d7e3668daed45bb8a750129d
