### ISSUE TITLE
Skip Advertisement problem

### ISSUE THREAD

**Issue by xmichele** [Ashish-Bansal/audio-only-youtube#65]
Hello,

my congrats for the project!
There seems to be some problems when I click to skip advertisement button, e.g. at the beginning of the video.
The advertisement audio continues, so I have to reload the whole page

**Comment by Ashish-Bansal** [comment]
Hi @xmichele,

I'm not aware of any solution for the same. In case anyone has ideas related to the same, feel free to drop them here.

**Comment by G3NZK1LZ** [comment]
Hey @Ashish-Bansal, I have been using Adblock Plus to avoid ads in youtube. Hope this can help.

**Comment by r12habh** [comment]
Adblock Plus does not remove the ads embedded in the website like Reddit ads. 
Better use YouTube Enhancer and uBlock Origin.

**Comment by Ashish-Bansal** [comment]
It would be best to use other extensions to remove ads rather than adding workaround here. Marking it as "wont-fix".
