### ISSUE TITLE
Chrome webstore link broken

### ISSUE THREAD

**Issue by roshanrathod** [Ashish-Bansal/audio-only-youtube#66]
Is this extension actively maintained? it's not available on chrome web store anymore.

https://chrome.google.com/webstore/detail/audio-only-youtube/pkocpiliahoaohbolmkelakpiphnllog

**Comment by Ashish-Bansal** [comment]
Hi @roshanrathod, 

It got removed yesterday from Chrome webstore due to some permission related issue. I'm talking to their customer support regarding the same.

**Comment by Ashish-Bansal** [comment]
It's back live again. Closing this issue.
