### ISSUE TITLE
Download as .mp3 button

### ISSUE THREAD

**Issue by caub** [Ashish-Bansal/audio-only-youtube#69]
I guess it wouldn't be too hard to allow downloading the audio stream

I could help later, will need to get familiar with the code first

Reason I ask is some services like https://ytmp3.cc/en13/ fail to download the audio with large videos

**Comment by vishalnandagopal** [comment]
Google will ban it from Chrome Webstore if Youtube downloader is implemented. Against the Youtube TOS.

Many download extensions state they don't work on Youtube
https://chrome.google.com/webstore/detail/video-downloader-pro/ccdikaeknpeokoejlpffihfmpfelakcg
https://chrome.google.com/webstore/detail/video-download-center/gcgmjkmcndbkdlimfkeidcmlgpjjgjhg

**Comment by Ashish-Bansal** [comment]
Right, that's the reason we can't support this feature.
