### ISSUE TITLE
Change Current Tab behaviour on icon click

### ISSUE THREAD

**Issue by varunjanga** [Ashish-Bansal/audio-only-youtube#8]
Hello, I would like to request a new feature. On clicking icon, reload current page(if it is youtube) with start time as current time. Thanks!

**Comment by bgeVam** [comment]
This is exactly what i wanted to suggest right now!

Maybe in
https://github.com/Ashish-Bansal/audio-only-youtube/blob/master/src/background.js#L139

insert:

    chrome.tabs.query({active: true, currentWindow: true}, function(tabs) {
        chrome.tabs.update(tabs[0].id, {url: tabs[0].url});
    });
