### ISSUE TITLE
Please, remove the permission to access the browser history

### ISSUE THREAD

**Issue by martin-braun** [Ashish-Bansal/audio-only-youtube#90]
Is the access to the browser history necessary? If not, I suggest to remove it, otherwise it looks suspicious to one or another.

**Comment by martin-braun** [comment]
Ok, I have done some research. It seems to be necessary to read tab information to determine if you are on YouTube or YouTube Music, thus getting this warning.

https://developer.chrome.com/docs/extensions/mv3/permission_warnings/#tabs

**Comment by bersbersbers** [comment]
What I'd like to know: in combination with the very restricted "Read and change your data on all (YouTube) sites", will this permission enable reading the browsing history only in tabs that currently are browsing YouTube - or all other tabs as well?
