### ISSUE TITLE
Music only doesn't work for live streams.

### ISSUE THREAD

**Issue by dhillonr** [Ashish-Bansal/audio-only-youtube#96]
I tried turning it on for live streaming video, it didn't work.

**Comment by mikeydevelops** [comment]
RTFD: https://chrome.google.com/webstore/detail/audio-only-youtube/pkocpiliahoaohbolmkelakpiphnllog

Can you please read the description?

Or are you too lazy? 

![image](https://user-images.githubusercontent.com/10907429/147384990-57e137de-9d7b-4e2a-ad28-9ee81ac272ca.png)

**Comment by dhillonr** [comment]
Sorry I didn't read the description. I am lazy.
